/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_PROTO_FRAMEPROFILE_PB_H_INCLUDED
#define PB_PROTO_FRAMEPROFILE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _frameProfile {
    uint32_t isr_trigger_number;
    uint64_t frame_begin_timestamp;
    uint64_t frame_render_done_timestamp;
    uint64_t frame_end_timestamp;
    uint32_t frame_number;
} frameProfile;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define frameProfile_init_default                {0, 0, 0, 0, 0}
#define frameProfile_init_zero                   {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define frameProfile_isr_trigger_number_tag      1
#define frameProfile_frame_begin_timestamp_tag   2
#define frameProfile_frame_render_done_timestamp_tag 3
#define frameProfile_frame_end_timestamp_tag     4
#define frameProfile_frame_number_tag            5

/* Struct field encoding specification for nanopb */
#define frameProfile_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   isr_trigger_number,   1) \
X(a, STATIC,   SINGULAR, UINT64,   frame_begin_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT64,   frame_render_done_timestamp,   3) \
X(a, STATIC,   SINGULAR, UINT64,   frame_end_timestamp,   4) \
X(a, STATIC,   SINGULAR, UINT32,   frame_number,      5)
#define frameProfile_CALLBACK NULL
#define frameProfile_DEFAULT NULL

extern const pb_msgdesc_t frameProfile_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define frameProfile_fields &frameProfile_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_FRAMEPROFILE_PB_H_MAX_SIZE         frameProfile_size
#define frameProfile_size                        45

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
